### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by SolalPirelli** [thedrhax-dockerfiles/jenkins-slave-android#2]
I'm currently writing scripts to automate Jenkins builds for a software engineering course at my university, so I'd like to use parts of your dockerfiles (which, as I've said in the other issue, are super useful!) to create my own, with whatever specific stuff I need.

However, right now, that's legally shaky, since your dockerfiles have no license; I don't think my university would be very happy with me just borrowing copyrighted-by-default stuff from the net.

Could you please add a license?

**Comment by TheDrHax** [comment]
I use GNU GPLv3 for most of my projects. Hope it will be suitable for you. If not, please reopen this issue and I will change the license ;)

**Comment by SolalPirelli** [comment]
@TheDrHax In case you're interested, https://github.com/sweng-epfl/jenkins-setup has a mostly-working Android 27 setup for Jenkins, including recording a video of the emulator during tests to see what goes wrong, as well as some aggressive code to make sure emulators start properly (since the Android emulator seems to randomly get stuck at the boot screen).

(by "mostly-working", I mean that it's a little buggy on the edges, and lacks support for some things, e.g. it seems Google Maps won't work on an emulator with emulated GPU...)
